on:
  push:
    branches:
      - master
      - main

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Prerequisites
      run: .\build\vsts-prerequisites.ps1
    - name: Validate
      run: .\build\vsts-validate.ps1
    - name: Build
      run: .\build\vsts-build.ps1 -ApiKey $env:APIKEY
      env:
        APIKEY: ${{ secrets.ApiKey }}
